export const SET_LOGIN = 'SET_LOGIN';
export const RESPONSE_SUCCESS = 'RESPONSE_SUCCESS';
export const RESPONSE_ERROR = 'RESPONSE_ERROR';
export const CHANGE_INDEX_OF_QUESTIONS = 'CHANGE_INDEX_OF_QUESTIONS';
